services:
    mongo:
        image: mongo:latest
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: robinson
            MONGO_INITDB_ROOT_PASSWORD: robinson123
            MONGO_INITDB_DATABASE: robinson
        volumes:
            - robinson-data:/data/db
        ports:
            - 27017:27017
    backend:
        build: "./backend"
        restart: unless-stopped
        volumes:
            - ./backend:/home/node/app
        environment:
            PORT: 3100
            NODE_ENV: development
            PROXY_ADDRESS: 1
        depends_on:
            - mongo
        ports:
            - 3100:3100
    frontend:
        build: "./frontend"
        restart: unless-stopped
        volumes:
            - ./frontend:/home/node/app
            - node_modules:/home/node/app/node_modules
        environment:
            PORT: 3000
            NODE_ENV: development
        depends_on:
            - backend
        ports:
            - 3000:3000
    mongo-web:
        image: mongo-express
        restart: unless-stopped
        ports:
            - 3200:8081
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "1"
        environment:
            ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
            ME_CONFIG_MONGODB_SERVER: "mongo"
            ME_CONFIG_BASICAUTH_USERNAME: robinson
            ME_CONFIG_BASICAUTH_PASSWORD: robinson123
            ME_CONFIG_MONGODB_AUTH_USERNAME: robinson
            ME_CONFIG_MONGODB_AUTH_PASSWORD: robinson123
        hostname: mongo-web
        depends_on:
            - mongo
volumes:
    robinson-data:
    node_modules:
