services:
    mongo:
        image: mongo:latest
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: robinson
            MONGO_INITDB_ROOT_PASSWORD: robinson123
            MONGO_INITDB_DATABASE: robinson
        volumes:
            - robinson-data:/data/db
        ports:
            - 27017:27017
    backend:
        build: "./backend"
        restart: unless-stopped
        volumes:
            - ./backend:/home/node/app
        environment:
            PORT: 3100
            NODE_ENV: development
            PROXY_ADDRESS: 1
        depends_on:
            - mongo
        ports:
            - 3100:3100
    frontend:
        build: "./frontend"
        restart: unless-stopped
        volumes:
            - ./frontend:/home/node/app
            - node_modules:/home/node/app/node_modules
        environment:
            PORT: 3000
            NODE_ENV: development
        depends_on:
            - backend
        ports:
            - 3000:3000
volumes:
    robinson-data:
    node_modules:
